version: '3.8'

services:
  flask:
    build: .
    container_name: deblurring-backend
    expose:
      - "5000"
    volumes:
      - ./static/uploads:/app/static/uploads  # persistent uploads
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    depends_on:
      - flask
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped